---
- name: Deploy NGINX Plus
  hosts: aws_instance
  become: true
  roles:
    - role: nginxinc.nginx
      vars:
        nginx_type: plus
        nginx_license:
          certificate: ../license/nginx-repo.crt
          key: ../license/nginx-repo.key
        nginx_remove_license: false
